"""Migracao 1

Revision ID: 31edd98553e4
Revises: 
Create Date: 2025-07-02 23:58:42.595184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31edd98553e4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alunos',
    sa.Column('id_aluno', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Email', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('data_nascimento', sa.Float(), nullable=True),
    sa.Column('CPF', sa.Float(), nullable=True),
    sa.Column('Endereço', sa.String(), nullable=True),
    sa.Column('Turma', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_aluno')
    )
    op.create_table('professores',
    sa.Column('id_professor', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_professor')
    )
    op.create_table('turma',
    sa.Column('id_turma', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alunos', sa.Integer(), nullable=True),
    sa.Column('ano', sa.String(), nullable=True),
    sa.Column('turno', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['alunos'], ['alunos.id_aluno'], ),
    sa.PrimaryKeyConstraint('id_turma')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turma')
    op.drop_table('professores')
    op.drop_table('alunos')
    # ### end Alembic commands ###
